version: "3"

services:
  postgres:
    image: "postgres:latest"
    container_name: herald-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    user: ${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./.etc/postgres-data:/var/lib/postgresql
    restart: unless-stopped
    command: -p ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "${POSTGRES_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 3

  qdrant:
    image: "qdrant/qdrant:latest"
    container_name: herald-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./.etc/qdrant_storage:/qdrant/storage:z
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis:6.2-alpine
    container_name: herald-redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./.etc/redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 3

  ollama:
    image: ollama/ollama
    container_name: herald-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./.etc/ollama:/root/.ollama

  backend:
    build:
      context: ./backend
    container_name: herald-backend
    volumes:
      - ./.etc/llama_index/:/tmp/llama_index/
      - ./.etc/uploads/:/app/uploads/
    depends_on:
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy

  # web:
  #   build:
  #     context: ./web
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./.etc/uploads/:/app/uploads/
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     qdrant:
  #       condition: service_healthy
