version: "3.5"

services:
  backend:
    build:
      context: ./server
    environment:
      LOGURU_COLORIZE: "true"
    volumes:
      - ./.etc/llama_index/:/tmp/llama_index/
      - ./.etc/nltk/:/root/nltk_data/
