version: "3"

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    user: ${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped
    command: -p ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "${POSTGRES_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
