llm: kobold
llm_kwargs:
  model: "gpt-3.5-turbo"
  base_url: https://entrance-futures-relief-managing.trycloudflare.com

embed_model: herald
embed_model_kwargs:
  model: "gpt-3.5-turbo"
  embed_url: https://retirement-paid-frost-turkish.trycloudflare.com/v1/embeddings
