llm: herald
llm_kwargs:
  base_url: https://c841-34-125-198-181.ngrok-free.app

embed_model: herald
embed_model_kwargs:
  model: "llama2"
  embed_url: https://c841-34-125-198-181.ngrok-free.app

max_sources: 3
min_similarity_score: 0.7
vector_store: milvus
vector_store_kwargs:
  uri: "http://172.17.0.1:19530"
  token: ""
