llm: openai
llm_kwargs:
  # base_url: https://483c-35-227-136-255.ngrok-free.app

embed_model: openai
embed_model_kwargs:
  # model: "llama2"
  # embed_url: https://483c-35-227-136-255.ngrok-free.app

max_sources: 5
min_similarity_score: 0.7
vector_store: milvus
vector_store_kwargs:
  uri: "http://172.17.0.1:19530"
  token: ""
